spring:
  application:
    name: temp
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/smartDoc
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
    show-sql: false

server:
  port: 8080

logging:
  level:
    jdbc: OFF
    jdbc.sqlonly: OFF
    jdbc.sqltiming: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF
    jdbc.audit: OFF
